name: artifacts
run-name: artifacts
on:
  workflow_dispatch:
jobs:
  get_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Get artifact
        run: |
          curl -k -o ./20MB.zip http://212.183.159.230/20MB.zip
          ls -la
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact-20MB.zip
          path: |
            ./20MB.zip
